name: Notify Slack on Push to Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        run: |
          payload=$(jq -n --arg repo "${{ github.repository }}" \
                          --arg pusher "${{ github.actor }}" \
                          --arg url "${{ github.event.head_commit.url }}" \
                          --arg message "${{ github.event.head_commit.message }}" \
                          '{
                            "blocks": [
                              {
                                "type": "section",
                                "text": {
                                  "type": "mrkdwn",
                                  "text": ":rocket: *Push to `main` detected!*"
                                }
                              },
                              {
                                "type": "section",
                                "fields": [
                                  {
                                    "type": "mrkdwn",
                                    "text": "*Repo:*\n\($repo)"
                                  },
                                  {
                                    "type": "mrkdwn",
                                    "text": "*Pusher:*\n\($pusher)"
                                  },
                                  {
                                    "type": "mrkdwn",
                                    "text": "*Message:*\n\($message)"
                                  }
                                ]
                              },
                              {
                                "type": "actions",
                                "elements": [
                                  {
                                    "type": "button",
                                    "text": {
                                      "type": "plain_text",
                                      "text": "View Commit"
                                    },
                                    "url": $url
                                  }
                                ]
                              }
                            ]
                          }')

          curl -X POST -H 'Content-type: application/json' \
               --data "$payload" \
               ${{ secrets.SLACK_WEBHOOK_URL }}
