[[headers]]
    for = "/*"
    [headers.values]
        X-Robots-Tag = "index, follow"

## Performance optimization plugins
#[[plugins]]
# ADDED GRIDSOME cache
#

# THIS WAS ALREADY HERE
#[[plugins]]
#package = "@netlify/plugin-lighthouse"
#  [plugins.inputs]
#  audit_url = "https://karmacall.com"

# ADDED THIS
#[[plugins]]
#package = "netlify-plugin-inline-critical-css"
#
# DID NOT ADD THIS SINCE GOOGLE HANDLES IT
#[[plugins]]
#package = "netlify-plugin-submit-sitemap"

# CORS headers for API requests
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

# Configure link checking plugin to ignore Google Tag Manager certificate errors
# TEMPORARILY COMMENTED OUT DUE TO BUG: Cannot destructure property 'operator' of 'fail.diag'
#[[plugins]]
#package = "netlify-plugin-checklinks"
#  [plugins.inputs]
#  # Skip external links from failing the build
#  skipPatterns = [
#    "www.googletagmanager.com", 
#    "googletagmanager.com",
#    "https://www.googletagmanager.com",
#    "https://googletagmanager.com"
#  ]
#  # Don't throw error on missing service worker
#  todoPatterns = [
#    "sw.js"
#  ]
#  # Disable checking external URLs to avoid certificate issues
#  checkExternal = false
