[[headers]]
    for = "/*"
    [headers.values]
        X-Robots-Tag = "index, follow"

# Add cache headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

## Performance optimization plugins

# Enable Lighthouse performance monitoring
[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
  audit_url = "https://karmacall.com"

# Inline critical CSS for faster rendering
[[plugins]]
package = "netlify-plugin-inline-critical-css"

# Optimize and compress images
[[plugins]]
package = "netlify-plugin-image-optim"

# Enable HTTP/2 server push for critical assets
[[plugins]]
package = "netlify-plugin-gatsby-cache"

# CORS headers for API requests
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

# Configure link checking plugin to ignore Google Tag Manager certificate errors
[[plugins]]
package = "netlify-plugin-checklinks"
  [plugins.inputs]
  # Skip external links from failing the build
  skipPatterns = [
    "www.googletagmanager.com", 
    "googletagmanager.com",
    "https://www.googletagmanager.com",
    "https://googletagmanager.com"
  ]
  # Don't throw error on missing service worker
  todoPatterns = [
    "sw.js"
  ]
  # Disable checking external URLs to avoid certificate issues
  checkExternal = false
